// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp2XPdp2k5mXV-omTduJDgYOeGzcgHXzo',
    appId: '1:386679401794:web:a04af5cce67c9ab21decdb',
    messagingSenderId: '386679401794',
    projectId: 'createplan-e5c22',
    authDomain: 'createplan-e5c22.firebaseapp.com',
    storageBucket: 'createplan-e5c22.appspot.com',
    measurementId: 'G-9NK0FY6BHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMuntTG0Mz9mKWRP57YXG9hL4RP_PCamk',
    appId: '1:386679401794:android:ca80d34fcebb08851decdb',
    messagingSenderId: '386679401794',
    projectId: 'createplan-e5c22',
    storageBucket: 'createplan-e5c22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtE6m-6mp3miAdR7TI48YShFDXoHn8_HM',
    appId: '1:386679401794:ios:89b13c548692f71e1decdb',
    messagingSenderId: '386679401794',
    projectId: 'createplan-e5c22',
    storageBucket: 'createplan-e5c22.appspot.com',
    iosClientId: '386679401794-om7horbb88vth6l6a6vedoc0df6e7b1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.createPlan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtE6m-6mp3miAdR7TI48YShFDXoHn8_HM',
    appId: '1:386679401794:ios:89b13c548692f71e1decdb',
    messagingSenderId: '386679401794',
    projectId: 'createplan-e5c22',
    storageBucket: 'createplan-e5c22.appspot.com',
    iosClientId: '386679401794-om7horbb88vth6l6a6vedoc0df6e7b1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.createPlan',
  );
}
